### ISSUE TITLE
hwmon variable not always set

### ISSUE THREAD

**Issue by rschetnan** [Shaped/amdpwrman#2]
The hwmon variable doesn't always get set, which results in errors. I fixed this in my cloned repository by setting hwmon wherever the gpu variable is set. There may be a more elegant solution to this problem, but it works for me. Otherwise, this seems like a good script so far.

**Comment by ForbiddenEra** [comment]
Hi,

Thanks for your kind comment.

This is possibly a bug introduced with the fix I did for issue #1 ..

Do you have other video adapters in your system from Intel or Nvidia or just AMD GPUs? Currently there may still be some other errors around other GPUs being installed.

**Comment by ForbiddenEra** [comment]
So this was totally a dumb-ass move on my part; forgetting to define that variable in each function/section and only in the show function.

This had the result of completely breaking everything about the script for everyone except showing stats, so I really appreciate you pointing out the issue.

I've pushed a fix out now. Let me know if it works or if you have any other issues.

**Comment by ForbiddenEra** [comment]
> There may be a more elegant solution to this problem, but it works for me. 

I suppose a better architecture would be to set the gpu and hwmon variables before jumping into any of the functions. It's been over 2 years since I wrote this and it was originally just meant to be a quick hack for myself.. but otherwise, that's exactly how I would've implemented this fix myself and indeed how I did - I didn't check your code but I'm sure it looks identical.

Of course, the more people use it, the more I'm motivated to clean it up/make it better..this repo has had more activity in the last few weeks than ever, so that's nice, I guess? :-)

**Comment by ForbiddenEra** [comment]
sooo.. I've decided to do a rewrite in NodeJS...

*[gpumgr](https://github.com/Shaped/gpumgr)* is the new project. It will eventually have a web interface and support all types of GPUs. Currently it implements the 'show' function and nothing else, but it's a start.

Thanks again for opening the issue and bringing it to my attention. If the update I made doesn't fix your problem, feel free to re-open the issue and I'll look into it but it should be fixed. Anyhow, the new app should be a lot better even though it's slightly more dependency heavy, there is a binary version available for ease of use, and otherwise the only requirement is NodeJS.
